### PR TITLE
Do not try to create the bean for the Gateway Connector when the gateway is disabled

### PR DESCRIPTION
**Pull request by psavva**
https://github.com/eu-digital-green-certificates/dgca-businessrule-service/issues/25

### CODE REVIEW

**Comment by psavva** [comment]
@SchulzeStTSI,

Could you please have this change reviewed?
The issue is settings the gateway connector to false without running the test spring boot profile.

**Comment by psavva** [comment]
Hi @mschulte-tsi 
What is the status of this PR?  
Please let me know if you need any changes to accept it, or go ahead and merge if all is good in the world.

Best Regards
Panayiotis Savva

**Comment by psavva** [comment]
@mschulte-tsi  Kind Reminder?

**Comment by daniel-eder** [comment]
@f11h @mschulte-tsi can one of you take a look at this? Thank you!

**Comment by slaurenz** [comment]
Hi @psavva,
I approved the PR #27 today, which includes the changes made to the file GatewayDataDownloadServiceImpl.java of this PR. The changes of the file GatewayDataDownloadBtpServiceImpl.java can not be approved, as the bean for btp download only exist when the btp profile is active. On the other hand the btp profile sets the gateway.connection.enabled to false, as it don't use the dgc-lib for downloading. With your changes the btp download bean would now also not be created, so there would be no download at all.
But I think your issue #25 should also be fixed with the PR #27 so that we can close this PR. 
Please let me know, if it fits your needs.

Thanks and regards
Simon

**Pull request closed without merging**
